networks:
  integration_network:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    pull_policy: always
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - integration_network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - integration_network
    volumes:
      - ollama-data:/root/.ollama
      - /etc/ssl/certs:/etc/ssl/certs

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: webui
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - integration_network
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ollama-webui-data:/app/backend/data
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - ollama

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    pull_policy: always
    restart: unless-stopped
    ports:
      - "5678:5678"
    networks:
      - integration_network
    depends_on:
      - postgres
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_SCHEMA=${DB_POSTGRESDB_SCHEMA}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_RESTRICT_FILE_ACCESS_TO=/swagger-html
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - n8n-data:/home/node/.n8n
      - ./certificates:/opt/custom-certificates
      - ./swagger-html:/swagger-html:rw

  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: postgresdb18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - integration_network
    volumes:
      - pgvector-data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - integration_network
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    pull_policy: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - integration_network
    restart: always

volumes:
  ollama-data:
    name: ollama_ollama-data
    external: true
  ollama-webui-data:
    name: ollama_ollama-webui-data
    external: true
  n8n-data:
    name: n8n_n8n-data
    external: true
  pgvector-data:
    name: n8n_pgvector18-data
    external: true
  pgadmin-data:
    name: n8n_pgadmin-data
    external: true
  portainer_data:
    name: portainer_portainer-data
    external: true
